'use client';
import { useState } from 'react';
import Image from 'next/image';

export default function Home() {
  const [input, setInput] = useState('');
  const [image, setImage] = useState('');
  const [audio, setAudio] = useState('');
  const [text, setText] = useState('');
  const [loading, setLoading] = useState(false);

  async function callApi() {
    try {
      if (!input) return;
      setLoading(true);
      setImage('');
      setAudio('');
      setText('');

      // Calling the API from our local endpoint api/gpt
      // where in route.ts everything is configured for api call
      // to open ai gpt4 and replicate ai
      const response = await fetch('/api/gpt', {
        method: 'POST',
        body: JSON.stringify({
          query: input,
        }),
      });

      const { data, type } = await response.json();
      if (type === 'image') {
        setImage(data[0]);
      }
      if (type === 'audio') {
        setImage(data);
      }
      if (type === 'text') {
        setImage(data);
      }
    } catch (e) {
      console.log('error: ', e);
    }
  }

  return (
    <main className="flex flex-col items-center justify-between p-24">
      <input
        type="text"
        className="px-3 py-1 text-black rounded"
        onChange={(e) => setInput(e.target.value)}
      />
      <button
        onClick={callApi}
        className="py-3 mt-3 mb-4 text-white bg-green-500 rounded-full cursor-pointer px-14"
      >
        Imagine
      </button>
      {image && (
        <Image
          src={image}
          alt="Image generated by AI"
          width={500}
          height={500}
        />
      )}
      {text && <p>{text}</p>}
      {audio && (
        <audio controls>
          <source src={audio} type="audio/mpeg" />
        </audio>
      )}
      {loading && <p>Loading...</p>}
    </main>
  );
}
